packaging_format = 2

id = "transmission"
name = "Transmission"
description.en = "Fast, Easy, and Free BitTorrent Client"
description.fr = "Client BitTorrent libre et rapide"

version = "3.00~ynh4"

maintainers = []

[upstream]
license = "GPL-3.0"
website = "https://www.transmissionbt.com"
admindoc = "https://github.com/transmission/transmission/wiki"
code = "https://github.com/transmission/transmission"
cpe = "cpe:2.3:a:transmissionbt:transmission"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/torrent"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "progress", "completed", "watched" ]

    [resources.permissions]
    main.url = "/"
    rpc.url = "/transmission/rpc"
    rpc.allowed = "visitors"
    rpc.show_tile = false
    rpc.protected = true

    [resources.ports]
    main.default = 9091
    main.exposed = "TCP"
    peer.default = 51413
    peer.exposed = "Both"

    [resources.apt]
    packages = "transmission-daemon, transmission-cli, transmission-common, acl"
