test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.multi"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.c07a09d8.name = "Upgrade from 2.94~ynh1"
    