test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.multi"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.e20afb4d5c7247df84a8a9a4d5d05ae7205aebb5.name = "Upgrade from 3.00~ynh1"