#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE DATA DIR
#=================================================

ynh_backup "$data_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/transmission-daemon/settings.json"

if [ -e /proc/sys/net/core/rmem_max ]
then
	ynh_backup "/etc/sysctl.d/90-transmission.conf"
fi

ynh_backup "/usr/share/transmission"

ynh_backup "/var/lib/transmission-daemon"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
