#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=transmission-daemon --action="stop" --log_path="systemd"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE TRANSMISSION CONFIGURATION
#=================================================

ynh_backup_if_checksum_is_different "/etc/transmission-daemon/settings.json"

ynh_replace --match="rpc-url\": \"${old_path%/}/transmission/" --replace="rpc-url\": \"${new_path%/}/transmission/" --file="/etc/transmission-daemon/settings.json"

ynh_store_file_checksum "/etc/transmission-daemon/settings.json"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=transmission-daemon --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
