#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
#=================================================

path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.
CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path_url

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN PORTS
#=================================================

port=$(ynh_find_port 9091)	# Cherche un port libre.
# Ouvre le port dans le firewall
ALL_QUIET sudo yunohost firewall allow --no-upnp TCP $port
ynh_app_setting_set $app port $port

peer_port=$(ynh_find_port 51413)	# Cherche un port libre.
# Ouvre le port dans le firewall
ALL_QUIET sudo yunohost firewall allow TCP $peer_port
ynh_app_setting_set $app peer_port $peer_port

#=================================================
# INSTALL TRANSMISSION
#=================================================

ynh_package_install transmission-daemon

#=================================================
# NGINX CONFIGURATION
#=================================================

# Add a "/" at the end of path_url for next commands
# To avoid a double / in the nginx config file.
[ "$path_url" = "/" ] || path_url=${path_url}/
ynh_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# CREATE DIRECTORIES
#=================================================

sudo mkdir -p /home/yunohost.transmission/{progress,completed,watched}

#=================================================
# SECURING FILES AND DIRECTORIES
#=================================================

sudo chown -R debian-transmission:www-data /home/yunohost.transmission/
sudo chown -R debian-transmission: /home/yunohost.transmission/{progress,watched}
sudo chmod -R 764 /home/yunohost.transmission
sudo chmod -R 777 /home/yunohost.transmission/watched

#=================================================
# CONFIGURE TRANSMISSION
#=================================================

# Transmission has to be stopped before modifying its config
sudo systemctl stop transmission-daemon

# Create a RPC password
rpcpassword=$(ynh_string_random)
ynh_app_setting_set $app rpcpassword "$rpcpassword"

ynh_replace_string "__RPC_PASSWORD_TO_CHANGE__" "$rpcpassword" ../conf/settings.json
ynh_replace_string "__PATH__" "$path_url" ../conf/settings.json
ynh_replace_string "__PEER_PORT__" "$peer_port" ../conf/settings.json
ynh_replace_string "__PORT__" "$port" ../conf/settings.json
sudo cp ../conf/settings.json /etc/transmission-daemon/settings.json

#=================================================
# STORE THE CHECKSUM OF THE CONFIG FILE
#=================================================

ynh_store_file_checksum /etc/transmission-daemon/settings.json

#=================================================
# YUNOHOST MULTIMEDIA INTEGRATION
#=================================================

ynh_multimedia_build_main_dir
# Set rights on transmission directory (parent need to be readable by other, and progress need to be writable by multimedia. Because files will move)
ynh_multimedia_addfolder "/home/yunohost.transmission" "share/Torrents"
# And share completed directory
ynh_multimedia_addfolder "/home/yunohost.transmission/completed" "share/Torrents"
# Share also watched directory, to allow to use it easily
ynh_multimedia_addfolder "/home/yunohost.transmission/watched" "share/Torrent to download"

#=================================================
# PATCH SOURCE TO ADD A DOWNLOAD BUTTON
#=================================================

sudo cp ../sources/extra_files/app/toolbar-downloads.png /usr/share/transmission/web/style/transmission/images/toolbar-downloads.png
sudo bash -c 'cat ../sources/extra_files/app/ynh_common.css >> /usr/share/transmission/web/style/transmission/common.css'
ynh_replace_string "<div id=\"toolbar-inspector\" title=\"Toggle Inspector\"></div>" "<div id=\"toolbar-inspector\" title=\"Toggle Inspector\"></div><div id=\"toolbar-separator\"></div><a href=\"../../downloads/\" id=\"toolbar-downloads\" title=\"Downloads\" target=\"_blank\"></a>" /usr/share/transmission/web/index.html

#=================================================
# GENERIC FINALISATION
#=================================================
# ENABLE SERVICE IN ADMIN PANEL
#=================================================

sudo yunohost service add transmission-daemon

#=================================================
# START TRANSMISSION
#=================================================

sudo systemctl start transmission-daemon

#=================================================
# RELOAD NGINX
#=================================================

sudo systemctl reload nginx
