#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." 

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
port=$(ynh_app_setting_get --app=$app --key=port)
peer_port=$(ynh_app_setting_get --app=$app --key=peer_port)
datadir=$(ynh_app_setting_get --app=$app --key=datadir)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status transmission-daemon >/dev/null 2>&1
then
	ynh_script_progression --message="Removing $app service..." --weight=8
	yunohost service remove transmission-daemon
fi

#=================================================
# REMOVE TRANSMISSION-DAEMON
#=================================================
ynh_script_progression --message="Removing transmission..." --weight=9

ynh_remove_app_dependencies

#=================================================
# REMOVE DATA DIR
#=================================================

# Remove the app data directory with the command `yunohost app remove transmission --purge`
if [ "${YNH_APP_PURGE:-0}" -eq 1 ]
then
  ynh_script_progression --message="Removing $app data directory..." --weight=2
  ynh_secure_remove --file="$datadir"
fi

#=================================================
# CLOSE THE PORTS
#=================================================

if yunohost firewall list | grep -q "\- $port$"
then
	ynh_script_progression --message="Closing port $port..." --weight=1
	ynh_exec_warn_less yunohost firewall disallow TCP $port
fi

if yunohost firewall list | grep -q "\- $peer_port$"
then
	ynh_script_progression --message="Closing port $peer_port..." --weight=1
	ynh_exec_warn_less yunohost firewall disallow Both $peer_port
fi

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --weight=2

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE DATA
#=================================================
ynh_script_progression --message="Removing transmission data..." --weight=2

# Web interface
ynh_secure_remove --file=/usr/share/transmission
# And data
ynh_secure_remove --file=/var/lib/transmission-daemon
# Kernel parameters
if [ -e /proc/sys/net/core/rmem_max ]
then
    ynh_secure_remove --file=/etc/sysctl.d/90-transmission.conf
    sysctl --load=/etc/sysctl.d/90-transmission.conf
fi

#=================================================
# GENERIC FINALISATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Removing the dedicated system user" --weight=1

# Delete a system user
ynh_system_user_delete --username=debian-transmission

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
