#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=transmission-daemon --action="stop" --log_path="systemd"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

ynh_config_add_nginx

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

if [ "$path" != "/" ]
then
	path_less="$path/"
else
	path_less="$path"
fi

_save_and_revert_rpc_password_hash_to_password

ynh_config_add --template="settings.json" --destination="/etc/transmission-daemon/settings.json"

chmod 400 "/etc/transmission-daemon/settings.json"
chown debian-transmission:debian-transmission "/etc/transmission-daemon/settings.json"

if [ -e /proc/sys/net/core/rmem_max ]
then
	ynh_config_add --template="90-transmission.conf" --destination="/etc/sysctl.d/90-transmission.conf"

	chmod 400 "/etc/sysctl.d/90-transmission.conf"
	chown debian-transmission:debian-transmission "/etc/sysctl.d/90-transmission.conf"

	sysctl --load=/etc/sysctl.d/90-transmission.conf
fi

#=================================================
# YUNOHOST MULTIMEDIA INTEGRATION
#=================================================
ynh_script_progression "Adding multimedia directories..."

# Remove possibly dangling symlinks created before the /home/yunohost.transmission -> /home/yunohost.app/transmission transition
# Use rm because ynh_safe_rm fails on dangling symlinks, see https://github.com/YunoHost/issues/issues/2253...
rm "$MEDIA_DIRECTORY/share/Torrents" || true
rm "$MEDIA_DIRECTORY/share/Torrent to download" || true

ynh_multimedia_build_main_dir

# Set rights on transmission directory (parent need to be readable by other, and progress need to be writable by multimedia. Because files will move)
ynh_multimedia_addfolder --source_dir="$data_dir" --dest_dir="share/Torrents"

# And share completed directory
ynh_multimedia_addfolder --source_dir="$data_dir/completed" --dest_dir="share/Torrents"

# Share also watched directory, to allow to use it easily
ynh_multimedia_addfolder --source_dir="$data_dir/watched" --dest_dir="share/Torrent to download"

#=================================================
# PATCH SOURCE TO ADD A DOWNLOAD BUTTON
#=================================================

cp ../sources/extra_files/app/toolbar-downloads.png /usr/share/transmission/web/style/transmission/images/toolbar-downloads.png
if ! grep --quiet "Inserted by Yunohost install script" /usr/share/transmission/web/style/transmission/common.css
then
	cat ../sources/extra_files/app/ynh_common.css >> /usr/share/transmission/web/style/transmission/common.css
fi

ynh_replace --match="<div id=\"toolbar-inspector\" title=\"Toggle Inspector\"></div>$" --replace="<div id=\"toolbar-inspector\" title=\"Toggle Inspector\"></div><div id=\"toolbar-separator\"></div><a href=\"../../downloads/\" id=\"toolbar-downloads\" title=\"Downloads\" target=\"_blank\"></a>" --file="/usr/share/transmission/web/index.html"

#=================================================
# SET DATA DIRECTORY PERMISSIONS
#=================================================
ynh_script_progression "Set data directory permissions..."

chmod -R 775 $data_dir
chmod -R 775 $data_dir/watched
chown -R debian-transmission:www-data "$data_dir"
chown -R debian-transmission: $data_dir/{progress,watched}

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add transmission-daemon --description="BitTorrent Client" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port_peer"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=transmission-daemon --action="start" --log_path="systemd"

#=================================================
# PATCH DOWNLOAD LOCATION IF DOWNLOAD PATH CHANGED
#=================================================
ynh_script_progression "Patching download locations..."

_patch_download_locations

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
